Repository dddom1kkk/AI-based-Communication-Tool-and-Traslator, pull requests merged in 2023-11, with the labels that each got.

#10 Create layout for main page
  Images/Icon_Speak.png
  Images/Icon_Type.png
  index.html
  styles/Index_style.css
Labels: main page, layout

#12 Add chat gpt functionality
  package-lock.json
  package.json
  script/text-to-translate.js
  text-to-translate.html
Labels: ChatGPT

#23 Added a navigation bar to speak-to-translate.html and text-to-transla…
  index.html
  speak-to-translate.html
  styles/Index_style.css
  styles/speak-to-translate-style.css
  styles/text-to-translate-style.css
  text-to-translate.html
Labels: layout

#43 #3. Settings button can open and close temporary section. Setup for Speech Recognition and Synthesis API page is done.
  script/speak-to-translate.js
  speak-to-translate.html
  styles/speak-to-translate-style.css
Labels: bug, layout

#40 Continuous Deployment
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  __mocks__/helperFunctions.js
  package-lock.json
  package.json
  script/text-to-translate.js
  script/text-to-translate.test.js
  text-to-translate.html
Labels: enhancement

#56 Fixed urls for all html, js and image references in speak to translat…
  Images/record-button-img.jpg
  index.html
  public/js/speak-to-generate.js
  public/speak-to-translate.html
  public/styles/speak-to-translate-style.css
  public/text-to-translate.html
  styles/speak-to-translate-style.css
Labels: enhancement, layout
